// Services catalog for Nodo — community mesh portal

const SERVICES = [
  {
    id: 'agenda',
    name: 'Agenda',
    tagline: 'Calendario comunitario',
    desc: 'Reuniones, mingas, asambleas y eventos del territorio.',
    glyph: 'calendar',
    category: 'Organización',
    size: '84 KB',
    offline: true,
    activity: 12,
    highlights: [
      { label: 'Minga de caminos — Vereda Alto Bonito', when: 'Sáb 27 · 6:00 a.m.', by: 'Junta de Acción Comunal' },
      { label: 'Asamblea mensual', when: 'Dom 28 · 2:00 p.m.', by: 'Nodo Travesías' },
      { label: 'Feria campesina', when: 'Sáb 4 may · 8:00 a.m.', by: 'ASPROCAF' },
    ],
  },
  {
    id: 'telefonia',
    name: 'Telefonía',
    tagline: 'Línea rural local',
    desc: 'Llamadas internas por la red comunitaria — sin operador, sin minutos.',
    glyph: 'phone',
    category: 'Comunicación',
    size: '1.2 MB',
    offline: true,
    activity: 38,
    highlights: [
      { label: 'Puesto de salud', when: 'Ext. 101', by: 'Disponible' },
      { label: 'Escuela El Carmen', when: 'Ext. 204', by: 'Disponible' },
      { label: 'Tienda doña Rosa', when: 'Ext. 312', by: 'Ocupado' },
    ],
  },
  {
    id: 'caseta',
    name: 'Caseta',
    tagline: 'Foro de la vereda',
    desc: 'Temas abiertos, acuerdos y novedades para toda la comunidad.',
    glyph: 'house',
    category: 'Organización',
    size: '220 KB',
    offline: true,
    activity: 7,
    highlights: [
      { label: 'Arreglo de la polea del acueducto', when: 'Hace 2 horas', by: 'Don Hernán' },
      { label: 'Se perdió una vaca en el paso alto', when: 'Ayer', by: 'Finca La Esperanza' },
      { label: 'Horarios del colectivo', when: 'Hace 3 días', by: 'Junta' },
    ],
  },
  {
    id: 'agrolink',
    name: 'Agrolink',
    tagline: 'Saberes del campo',
    desc: 'Calendario lunar, siembras, recetas de abono y remedios para el cultivo.',
    glyph: 'sprout',
    category: 'Campo',
    size: '3.4 MB',
    offline: true,
    activity: 21,
    highlights: [
      { label: 'Luna menguante — podar café', when: 'Esta semana', by: 'Calendario' },
      { label: 'Biopreparado para roya', when: 'Receta #14', by: 'Don Gilberto' },
      { label: 'Semillas nativas disponibles', when: 'Banco local', by: '7 variedades' },
    ],
  },
  {
    id: 'rapicampo',
    name: 'Rapi Campo',
    tagline: 'Apoyo mutuo',
    desc: 'Pide o ofrece una mano: cargar, cosechar, transportar, cuidar.',
    glyph: 'hands',
    category: 'Apoyo',
    size: '140 KB',
    offline: true,
    activity: 4,
    highlights: [
      { label: 'Necesito ayuda con 8 bultos', when: 'Vereda Travesías', by: 'Marta R. · paga en yuca' },
      { label: 'Ofrezco mula medio día', when: 'Sáb tarde', by: 'Eliécer · $15.000' },
      { label: 'Busco quien cuide niña', when: 'Miér próx.', by: 'Familia Ortiz' },
    ],
  },
  {
    id: 'alertas',
    name: 'Alertas',
    tagline: 'Avisos del territorio',
    desc: 'Seguridad, clima, caminos cerrados y emergencias en tiempo real.',
    glyph: 'bell',
    category: 'Seguridad',
    size: '60 KB',
    offline: true,
    activity: 2,
    live: true,
    highlights: [
      { label: 'Derrumbe en km 14 — vía al pueblo', when: 'Hace 40 min', by: '⚠ Activa' },
      { label: 'Lluvias fuertes esta tarde', when: 'Pronóstico', by: 'Radio comunitaria' },
      { label: 'Quema controlada autorizada', when: 'Vereda Las Palmas', by: 'Bomberos' },
    ],
  },
  {
    id: 'trueque',
    name: 'Trueque',
    tagline: 'Cambio sin plata',
    desc: 'Intercambia lo que te sobra por lo que te hace falta.',
    glyph: 'swap',
    category: 'Economía',
    size: '180 KB',
    offline: true,
    activity: 18,
    highlights: [
      { label: 'Cambio miel por yuca', when: '2 botellas', by: 'Apiario La Colmena' },
      { label: 'Cambio gallinas por maíz', when: '3 aves', by: 'Finca San Antonio' },
      { label: 'Cambio clases de guitarra', when: 'Por hortalizas', by: 'Profe Mateo' },
    ],
  },
  {
    id: 'kiwix',
    name: 'Kiwix',
    tagline: 'Biblioteca sin internet',
    desc: 'Wikipedia, manuales y libros escolares guardados en el nodo.',
    glyph: 'book',
    category: 'Conocimiento',
    size: '2.1 GB',
    offline: true,
    activity: 96,
    highlights: [
      { label: 'Wikipedia — edición escolar', when: 'Español', by: '12.400 artículos' },
      { label: 'Manuales agrícolas FAO', when: 'PDF', by: '38 títulos' },
      { label: 'Cuentos del Pacífico', when: 'Audio', by: '26 relatos' },
    ],
  },
  {
    id: 'primaux',
    name: 'Primaux',
    tagline: 'Primeros auxilios',
    desc: 'Guía rápida ilustrada para atender urgencias antes del puesto de salud.',
    glyph: 'cross',
    category: 'Salud',
    size: '95 KB',
    offline: true,
    activity: 3,
    highlights: [
      { label: 'Mordedura de serpiente', when: 'Protocolo', by: 'Paso a paso' },
      { label: 'Cómo hacer un torniquete', when: 'Video 2 min', by: 'Cruz Roja' },
      { label: 'Lista botiquín de vereda', when: 'Documento', by: '14 insumos' },
    ],
  },
  {
    id: 'medicina',
    name: 'Medicina',
    tagline: 'Saberes tradicionales',
    desc: 'Plantas, preparaciones y prácticas de cuidado del territorio.',
    glyph: 'leaf',
    category: 'Salud',
    size: '410 KB',
    offline: true,
    activity: 9,
    highlights: [
      { label: 'Matarratón — fiebre', when: 'Infusión', by: 'Doña Evelia' },
      { label: 'Sábila — quemaduras', when: 'Tópico', by: 'Tradición' },
      { label: 'Baños de albahaca', when: 'Ritual', by: 'Territorio' },
    ],
  },
  {
    id: 'ecomerce',
    name: 'Mercado',
    tagline: 'Tienda del nodo',
    desc: 'Productos de las veredas: café, panela, queso, artesanías.',
    glyph: 'bag',
    category: 'Economía',
    size: '260 KB',
    offline: false,
    activity: 14,
    highlights: [
      { label: 'Café pergamino — 1 arroba', when: '$180.000', by: 'Finca El Porvenir' },
      { label: 'Panela cuadrada', when: '$3.500 / unidad', by: 'Trapiche La Loma' },
      { label: 'Mochila tejida', when: '$95.000', by: 'Taller Las Manos' },
    ],
  },
];

// Ticker items (live alerts, simulated)
const TICKER = [
  '⚠ Derrumbe km 14 — paso cerrado',
  '◉ 43 vecinos conectados al nodo',
  '☁ Lluvias fuertes 3:00 p.m.',
  '✚ Brigada de vacunación mañana',
  '◎ Última sincronización: hace 12 min',
  '♺ Minga de caminos sábado 6 a.m.',
];

window.SERVICES = SERVICES;
window.TICKER = TICKER;
